version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solvex-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.prod.back
    environment:
      - PORT=8000
    networks:
      - solvex-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solvex-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - .env.prod.front
    depends_on:
      - backend
    networks:
      - solvex-network

networks:
  solvex-network:
    driver: bridge
